create table energiatodistus (
  id int generated by default as identity primary key,
  rakennus_nimi varchar(50),
  rakennus_tunnus varchar(50),
  rakennus_katuosoite_fi varchar(50),
  rakennus_postinumero integer
);
