create table kayttaja (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etunimi text NOT NULL,
  sukunimi text NOT NULL,
  email text NOT NULL,
  puhelin text NOT NULL,
  passivoitu boolean DEFAULT false NOT NULL,
  rooli int DEFAULT 0 NOT NULL,
  login timestamp with time zone,
  ensitallennus boolean DEFAULT FALSE,
  cognito_id text
);

create or replace function current_kayttaja_id() returns int as $$
begin
  return split_part(current_setting('application_name'), '@', 1) :: int;
end;
$$ language plpgsql immutable;
