create table kayttaja (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etunimi text NOT NULL,
  sukunimi text NOT NULL,
  henkilotunnus text NOT NULL,
  email text NOT NULL,
  puhelinnumero text,
  katuosoite text NOT NULL,
  postinumero text NOT NULL,
  postitoimipaikka text NOT NULL,
  maa char(2) REFERENCES country (id),
  passivoitu boolean NOT NULL DEFAULT false,
  rooli int NOT NULL default 0,
  cognito_id TEXT
);
