create table kayttaja (
  id int generated by default as identity primary key,
  etunimi text not null,
  sukunimi text not null,
  email text not null unique,
  puhelin text not null,
  passivoitu boolean default false not null,
  rooli int default 0 not null,
  login timestamp with time zone,
  ensitallennus boolean default false,
  henkilotunnus text unique,
  cognito_id text,
  virtu$localid text,
  virtu$organisaatio text,
  constraint kayttaja_virtu_key unique (virtu$localid, virtu$organisaatio)
);

create or replace function current_kayttaja_id() returns int as $$
begin
  return split_part(current_setting('application_name'), '@', 1) :: int;
end;
$$ language plpgsql immutable;
