(ns solita.etp.service.energiatodistus-xlsx
  (:require [clojure.java.io :as io]
            [solita.common.xlsx :as xlsx]
            [solita.etp.service.energiatodistus :as energiatodistus-service]))

(def tmp-dir "tmp/")

(def mappings
  [["Todistustunnus" [:id]]
   ["Rakennuksen nimi"[:perustiedot :nimi]]
   ["Rakennustunnus" [:perustiedot :rakennustunnus]]
   ["Kiinteistötunnus" [:perustiedot :kiinteistotunnus]]
   ["Katuosoite suomeksi" [:perustiedot :katuosoite-fi]]
   ["Katuosoite ruotsiksi" [:perustiedot :katuosoite-sv]]
   ["Postinumero" [:perustiedot :postinumero]]
   ["Julkinen rakennus"]
   ["Uudisrakennus"]
   ["Laatimisvaihe"]
   ["Havainnointikäynnin päivämäärä"]
   ["Rakennuksen osa"]
   ["Rakennuksen valmistumisvuosi"]
   ["Todistuksen laatimispäivä"]
   ["Viimeinen voimassaolopäivä"]
   ["Rakennusluokka"]
   ["Rakennuksen käyttötarkoitusluokka"]
   ["E-luku"]
   ["E-luvun vaatimustaso"]
   ["E-luokka"]
   ["Keskeiset huomiot (fi)"]
   ["Keskeiset huomiot (sv)"]
   ["Laatija"]
   ["Tilaaja"]
   ["Tarkastettu viimeksi"]
   ["Katsottu viimeksi"]
   ["Lisämerkinnät (fi)"]
   ["Lisämerkinnät (sv)"]
   ["Tila"]
   ["Versio"]
   ["Lukemattomia viestejä"]
   ["Yritys"]
   ["Yrityksen katuosoite"]
   ["Yrityksen postinumero"]
   ["Yrityksen postitoimipaikka"]
   ["Laskun numero"]
   ["Energiatodistuksen kieli"]
   ["Lämmitetty nettoala"]
   ["Ilmanvuotoluku q_50"]
   ["Ulkoseinät A"]
   ["Ulkoseinät U"]
   ["Ulkoseinät U × A"]
   ["Ulkoseinien osuus lämpöhäviöistä"]
   ["Yläpohja A"]
   ["Yläpohja U"]
   ["Yläpohja U × A"]
   ["Yläpohjan osuus lämpöhäviöistä"]
   ["Alapohja A"]
   ["Alapohja U"]
   ["Alapohja U × A"]
   ["Alapohjan osuus lämpöhäviöistä"]
   ["Ikkunat A"]
   ["Ikkunat U"]
   ["Ikkunat U × A"]
   ["Ikkunoiden osuus lämpöhäviöistä"]
   ["Ulko-ovet A"]
   ["Ulko-ovet U"]
   ["Ulko-ovet U × A"]
   ["Ulko-ovien osuus lämpöhäviöistä"]
   ["Kylmäsillat A"]
   ["Kylmäsillat U"]
   ["Kylmäsillat U × A"]
   ["Kylmäsiltojen osuus lämpöhäviöistä"]
   ["Pohjoinen A"]
   ["Pohjoinen U"]
   ["Pohjoinen g_kohtisuora-arvo"]
   ["Koillinen A"]
   ["Koillinen U"]
   ["Koillinen g_kohtisuora-arvo"]
   ["Itä A"]
   ["Itä U"]
   ["Itä g_kohtisuora-arvo"]
   ["Kaakko A"]
   ["Kaakko U"]
   ["Kaakko g_kohtisuora-arvo"]
   ["Etelä A"]
   ["Etelä U"]
   ["Etelä g_kohtisuora-arvo"]
   ["Lounas A"]
   ["Lounas U"]
   ["Lounas g_kohtisuora-arvo"]
   ["Länsi A"]
   ["Länsi U"]
   ["Länsi g_kohtisuora-arvo"]
   ["Luode A"]
   ["Luode U"]
   ["Luode g_kohtisuora-arvo"]
   ["Ilmanvaihtojärjestelmän kuvaus"]
   ["Ilmanvaihtojärjestelmän kuvaus (sv)"]
   ["Pääilmanvaihtokoneet, tulo"]
   ["Pääilmanvaihtokoneet, poisto"]
   ["Pääilmanvaihtokoneet, järjestelmän SFP-luku"]
   ["Pääilmanvaihtokoneet, LTO:n lämpötilasuhde"]
   ["Pääilmanvaihtokoneet, jäätymisenesto"]
   ["Erillispoistot, tulo"]
   ["Erillispoistot, poisto"]
   ["Erillispoistot, järjestelmän SFP-luku"]
   ["Ilmanvaihto, tulo"]
   ["Ilmanvaihto, poisto"]
   ["Järjestelmän SFP-luku"]
   ["Rakennuksen ilmanvaihtojärjestelmän LTO:n vuosihyötysuhde:"]
   ["Lämmitysjärjestelmän kuvaus"]
   ["Lämmitysjärjestelmän kuvaus (sv)"]
   ["Tilat: Tuoton hyötysuhde"]
   ["Tilat: Jaon ja luovutuksen hyötysuhde"]
   ["Tilat: Lämpökerroin"]
   ["Tilat: Apulaitteiden sähkönkäyttö"]
   ["Käyttövesi: Tuoton hyötysuhde"]
   ["Käyttövesi: Jaon ja luovutuksen hyötysuhde"]
   ["Käyttövesi: Lämpökerroin"]
   ["Käyttövesi: Apulaitteiden sähkönkäyttö"]
   ["Varaavien tulisijojen määrä"]
   ["Varaavien tulisijojen tuotto"]
   ["Ilmalämpöpumppujen määrä"]
   ["Ilmalämpöpumppujen tuotto"]
   ["Jäähdytyskauden painotettu kylmäkerroin"]
   ["Ominaiskulutus"]
   ["Lämmitysenergian nettotarve"]
   ["Selite 1 (fi)"]
   ["Selite 1 (sv)"]
   ["Käyttöaste 1"]
   ["Henkilöt 1"]
   ["Kuluttajalaitteet 1"]
   ["Valaistus 1"]
   ["Selite 2 (fi)"]
   ["Selite 2 (sv)"]
   ["Käyttöaste 2"]
   ["Henkilöt 2"]
   ["Kuluttajalaitteet 2"]
   ["Valaistus 2"]
   ["Selite 3 (fi)"]
   ["Selite 3 (sv)"]
   ["Käyttöaste 3"]
   ["Henkilöt 3"]
   ["Kuluttajalaitteet 3"]
   ["Valaistus 3"]
   ["Käytettävä energiamuoto 1"]
   ["Laskettu ostoenergia 1"]
   ["Kerroin 1"]
   ["Painotettu vuosikulutus 1"]
   ["Painotettu neliövuosikulutus 1"]
   ["Käytettävä energiamuoto 2"]
   ["Laskettu ostoenergia 2"]
   ["Kerroin 2"]
   ["Painotettu vuosikulutus 2"]
   ["Painotettu neliövuosikulutus 2"]
   ["Käytettävä energiamuoto 3"]
   ["Laskettu ostoenergia 3"]
   ["Kerroin 3"]
   ["Painotettu vuosikulutus 3"]
   ["Painotettu neliövuosikulutus 3"]
   ["Energianlähde 1"]
   ["Vakioidulla käytöllä laskettu ostoenergia 1"]
   ["Energiamuodon kerroin 1"]
   ["Painotettu vuosikulutus 1"]
   ["Painotettu neliövuosikulutus 1"]
   ["Energianlähde 2"]
   ["Vakioidulla käytöllä laskettu ostoenergia 2"]
   ["Energiamuodon kerroin 2"]
   ["Painotettu vuosikulutus 2"]
   ["Painotettu neliövuosikulutus 2"]
   ["Energianlähde 3"]
   ["Vakioidulla käytöllä laskettu ostoenergia 3"]
   ["Energiamuodon kerroin 3"]
   ["Painotettu vuosikulutus 3"]
   ["Painotettu neliövuosikulutus 3"]
   ["Energianlähde 4"]
   ["Vakioidulla käytöllä laskettu ostoenergia 4"]
   ["Energiamuodon kerroin 4"]
   ["Painotettu vuosikulutus 4"]
   ["Painotettu neliövuosikulutus 4"]
   ["Energianlähde 5"]
   ["Vakioidulla käytöllä laskettu ostoenergia 5"]
   ["Energiamuodon kerroin 5"]
   ["Painotettu vuosikulutus 5"]
   ["Painotettu neliövuosikulutus 5"]
   ["Energiamuoto 1 (fi)"]
   ["Energiamuoto 1 (sv)"]
   ["Vuosikulutus 1"]
   ["Neliövuosikulutus 1"]
   ["Energiamuoto 2 (fi)"]
   ["Energiamuoto 2 (sv)"]
   ["Vuosikulutus 2"]
   ["Neliövuosikulutus 2"]
   ["Energiamuoto 3 (fi)"]
   ["Energiamuoto 3 (sv)"]
   ["Vuosikulutus 3"]
   ["Neliövuosikulutus 3"]
   ["Energiamuoto 4 (fi)"]
   ["Energiamuoto 4 (sv)"]
   ["Vuosikulutus 4"]
   ["Neliövuosikulutus 4"]
   ["Energiamuoto 5 (fi)"]
   ["Energiamuoto 5 (sv)"]
   ["Vuosikulutus 5"]
   ["Neliövuosikulutus 5"]
   ["Energiamuoto 6 (fi)"]
   ["Energiamuoto 6 (sv)"]
   ["Vuosikulutus 6"]
   ["Neliövuosikulutus 6"]
   ["Tilojen lämmitys – Sähkö"]
   ["Tilojen lämmitys – Lämpö"]
   ["Tuloilman lämmitys – Sähkö"]
   ["Tuloilman lämmitys – Lämpö"]
   ["Käyttöveden valmistus – Sähkö"]
   ["Käyttöveden valmistus – Lämpö"]
   ["Käyttöveden valmistus – Kaukojäähdytys"]
   ["Ilmanvaihto – Sähkö"]
   ["Jäähdytys – Sähkö"]
   ["Jäähdytys – Lämpö"]
   ["Jäähdytys – Kaukojäähdytys"]
   ["Kuluttajalaitteet ja valaistus – Sähkö"]
   ["Yhteensä Sähkö"]
   ["Yhteensä Lämpö"]
   ["Yhteensä Kaukojäähdytys"]
   ["Tilojen lämmitys – Vuosikulutus"]
   ["Tilojen lämmitys – Neliövuosikulutus"]
   ["Ilmanvaihdon lämmitys – Vuosikulutus"]
   ["Ilmanvaihdon lämmitys – Neliövuosikulutus"]
   ["Käyttöveden valmistus – Vuosikulutus"]
   ["Käyttöveden valmistus – Neliövuosikulutus"]
   ["Jäähdytys – Vuosikulutus"]
   ["Jäähdytys – Neliövuosikulutus"]
   ["Aurinko – Vuosikulutus"]
   ["Aurinko – Neliövuosikulutus"]
   ["Ihmiset – Vuosikulutus"]
   ["Ihmiset – Neliövuosikulutus"]
   ["Kuluttajalaitteet – Vuosikulutus"]
   ["Kuluttajalaitteet – Neliövuosikulutus"]
   ["Valaistus – Vuosikulutus"]
   ["Valaistus – Neliövuosikulutus"]
   ["Lämmin käyttövesi – vuosikulutus"]
   ["Lämmin käyttövesi – neliövuosikulutus"]
   ["Laskentatyökalun nimi ja versionumero"]
   ["Ostetun kaukolämpöenergian vuosikulutus"]
   ["Ostetun kaukolämpöenergian neliövuosikulutus"]
   ["Ostetun sähköenergian (kokonaissähkö) vuosikulutus"]
   ["Ostetun sähköenergian (kokonaissähkö) neliövuosikulutus"]
   ["Ostetun sähköenergian (kiinteistö) vuosikulutus"]
   ["Ostetun sähköenergian (kiinteistö) neliövuosikulutus"]
   ["Ostetun sähköenergian (kayttaja) vuosikulutus"]
   ["Ostetun sähköenergian (kayttaja) neliovuosikulutus"]
   ["Ostetun kaukojäähdytysenergian vuosikulutus"]
   ["Ostetun kaukojäähdytysenergian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 1)"]
   ["Ostetun (vapaasti syötettävä 1) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 1) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 2)"]
   ["Ostetun (vapaasti syötettävä 2) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 2) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 3)"]
   ["Ostetun (vapaasti syötettävä 3) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 3) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 4)"]
   ["Ostetun (vapaasti syötettävä 4) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 4) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 5)"]
   ["Ostetun (vapaasti syötettävä 5) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 5) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 6)"]
   ["Ostetun (vapaasti syötettävä 6) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 6) energian neliövuosikulutus"]
   ["Energianlähde 1"]
   ["polttoaineen määrä vuodessa 1"]
   ["yksikkö 1"]
   ["muunnoskerroin kWh:ksi 1"]
   ["Vuosikulutus 1"]
   ["Neliövuosikulutus 1"]
   ["Energianlähde 2"]
   ["polttoaineen määrä vuodessa 2"]
   ["yksikkö 2"]
   ["muunnoskerroin kWh:ksi 2"]
   ["Vuosikulutus 2"]
   ["Neliövuosikulutus 2"]
   ["Energianlähde 3"]
   ["polttoaineen määrä vuodessa 3"]
   ["yksikkö 3"]
   ["muunnoskerroin kWh:ksi 3"]
   ["Vuosikulutus 3"]
   ["Neliövuosikulutus 3"]
   ["Energianlähde 4"]
   ["polttoaineen määrä vuodessa 4"]
   ["yksikkö 4"]
   ["muunnoskerroin kWh:ksi 4"]
   ["Vuosikulutus 4"]
   ["Neliövuosikulutus 4"]
   ["Energianlähde 5"]
   ["polttoaineen määrä vuodessa 5"]
   ["yksikkö 5"]
   ["muunnoskerroin kWh:ksi 5"]
   ["Vuosikulutus 5"]
   ["Neliövuosikulutus 5"]
   ["Energianlähde 6"]
   ["polttoaineen määrä vuodessa 6"]
   ["yksikkö 6"]
   ["muunnoskerroin kWh:ksi 6"]
   ["Vuosikulutus 6"]
   ["Neliövuosikulutus 6"]
   ["Energianlähde 7"]
   ["polttoaineen määrä vuodessa 7"]
   ["yksikkö 7"]
   ["muunnoskerroin kWh:ksi 7"]
   ["Vuosikulutus 7"]
   ["Neliövuosikulutus 7"]
   ["Energianlähde 8"]
   ["polttoaineen määrä vuodessa 8"]
   ["yksikkö 8"]
   ["muunnoskerroin kWh:ksi 8"]
   ["Vuosikulutus 8"]
   ["Neliövuosikulutus 8"]
   ["Energianlähde 9"]
   ["polttoaineen määrä vuodessa 9"]
   ["yksikkö 9"]
   ["muunnoskerroin kWh:ksi 9"]
   ["Vuosikulutus 9"]
   ["Neliövuosikulutus 9"]
   ["Energianlähde 10"]
   ["polttoaineen määrä vuodessa 10"]
   ["yksikkö 10"]
   ["muunnoskerroin kWh:ksi 10"]
   ["Vuosikulutus 10"]
   ["Neliövuosikulutus 10"]
   ["Energianlähde 11"]
   ["polttoaineen määrä vuodessa 11"]
   ["yksikkö 11"]
   ["muunnoskerroin kWh:ksi 11"]
   ["Vuosikulutus 11"]
   ["Neliövuosikulutus 11"]
   ["Energianlähde 12"]
   ["polttoaineen määrä vuodessa 12"]
   ["yksikkö 12"]
   ["muunnoskerroin kWh:ksi 12"]
   ["Vuosikulutus 12"]
   ["Neliövuosikulutus 12"]
   ["Energianlähde 13"]
   ["polttoaineen määrä vuodessa 13"]
   ["yksikkö 13"]
   ["muunnoskerroin kWh:ksi 13"]
   ["Vuosikulutus 13"]
   ["Neliövuosikulutus 13"]
   ["Energianlähde 14"]
   ["polttoaineen määrä vuodessa 14"]
   ["yksikkö 14"]
   ["muunnoskerroin kWh:ksi 14"]
   ["Vuosikulutus 14"]
   ["Neliövuosikulutus 14"]
   ["Toteutunut sähkön vuosikulutus"]
   ["Toteutunut sähkön neliövuosikulutus"]
   ["Toteutunut kaukolämmön vuosikulutus"]
   ["Toteutunut kaukolämmön neliövuosikulutus"]
   ["Toteutunut polttoaineiden vuosikulutus"]
   ["Toteutunut polttoaineiden neliövuosikulutus"]
   ["Toteutunut kaukojäähdytyksen vuosikulutus"]
   ["Toteutunut kaukojäähdytyksen neliövuosikulutus"]
   ["Toteutunut vuosikulutus yhteensä"]
   ["Toteutunut neliövuosikulutus yhteensä"]
   ["Huomiot - ulkoseinät, ulko-ovet ja ikkunat (fi)"]
   ["Huomiot - ulkoseinät, ulko-ovet ja ikkunat (sv)"]
   ["Toimenpide-ehdotus (fi) 1"]
   ["Toimenpide-ehdotus (sv) 1"]
   ["Lämpö, ostoenergian muutos 1"]
   ["Sähkö, ostoenergian muutos 1"]
   ["Jäähdytys, ostoenergian muutos 1"]
   ["E-luvun muutos 1"]
   ["Toimenpide-ehdotus (fi) 2"]
   ["Toimenpide-ehdotus (sv) 2"]
   ["Lämpö, ostoenergian muutos 2"]
   ["Sähkö, ostoenergian muutos 2"]
   ["Jäähdytys, ostoenergian muutos 2"]
   ["E-luvun muutos 2"]
   ["Toimenpide-ehdotus (fi) 3"]
   ["Toimenpide-ehdotus (sv) 3"]
   ["Lämpö, ostoenergian muutos 3"]
   ["Sähkö, ostoenergian muutos 3"]
   ["Jäähdytys, ostoenergian muutos 3"]
   ["E-luvun muutos 3"]
   ["Huomiot ylä- ja alapohja (fi)"]
   ["Huomiot ylä- ja alapohja (sv)"]
   ["Toimenpide-ehdotus (fi) 1"]
   ["Toimenpide-ehdotus (sv) 1"]
   ["Lämpö, ostoenergian muutos 1"]
   ["Sähkö, ostoenergian muutos 1"]
   ["Jäähdytys, ostoenergian muutos 1"]
   ["E-luvun muutos 1"]
   ["Toimenpide-ehdotus (fi) 2"]
   ["Toimenpide-ehdotus (sv) 2"]
   ["Lämpö, ostoenergian muutos 2"]
   ["Sähkö, ostoenergian muutos 2"]
   ["Jäähdytys, ostoenergian muutos 2"]
   ["E-luvun muutos 2"]
   ["Toimenpide-ehdotus (fi) 3"]
   ["Toimenpide-ehdotus (sv) 3"]
   ["Lämpö, ostoenergian muutos 3"]
   ["Sähkö, ostoenergian muutos 3"]
   ["Jäähdytys, ostoenergian muutos 3"]
   ["E-luvun muutos 3"]
   ["Huomiot - lämmitys (fi)"]
   ["Huomiot - lämmitys (sv)"]
   ["Toimenpide-ehdotus (fi) 1"]
   ["Toimenpide-ehdotus (sv) 1"]
   ["Lämpö, ostoenergian muutos 1"]
   ["Sähkö, ostoenergian muutos 1"]
   ["Jäähdytys, ostoenergian muutos 1"]
   ["E-luvun muutos 1"]
   ["Toimenpide-ehdotus (fi) 2"]
   ["Toimenpide-ehdotus (sv) 2"]
   ["Lämpö, ostoenergian muutos 2"]
   ["Sähkö, ostoenergian muutos 2"]
   ["Jäähdytys, ostoenergian muutos 2"]
   ["E-luvun muutos 2"]
   ["Toimenpide-ehdotus (fi) 3"]
   ["Toimenpide-ehdotus (sv) 3"]
   ["Lämpö, ostoenergian muutos 3"]
   ["Sähkö, ostoenergian muutos 3"]
   ["Jäähdytys, ostoenergian muutos 3"]
   ["E-luvun muutos 3"]
   ["Huomiot - ilmanvaihto ja ilmastointi (fi)"]
   ["Huomiot - ilmanvaihto ja ilmastointi (sv)"]
   ["Toimenpide-ehdotus (fi) 1"]
   ["Toimenpide-ehdotus (sv) 1"]
   ["Lämpö, ostoenergian muutos 1"]
   ["Sähkö, ostoenergian muutos 1"]
   ["Jäähdytys, ostoenergian muutos 1"]
   ["E-luvun muutos 1"]
   ["Toimenpide-ehdotus (fi) 2"]
   ["Toimenpide-ehdotus (sv) 2"]
   ["Lämpö, ostoenergian muutos 2"]
   ["Sähkö, ostoenergian muutos 2"]
   ["Jäähdytys, ostoenergian muutos 2"]
   ["E-luvun muutos 2"]
   ["Toimenpide-ehdotus (fi) 3"]
   ["Toimenpide-ehdotus (sv) 3"]
   ["Lämpö, ostoenergian muutos 3"]
   ["Sähkö, ostoenergian muutos 3"]
   ["Jäähdytys, ostoenergian muutos 3"]
   ["E-luvun muutos 3"]
   ["Huomiot - valaistus ja muut järjestelmät (fi)"]
   ["Huomiot - valaistus ja muut järjestelmät (sv)"]
   ["Toimenpide-ehdotus (fi) 1"]
   ["Toimenpide-ehdotus (sv) 1"]
   ["Lämpö, ostoenergian muutos 1"]
   ["Sähkö, ostoenergian muutos 1"]
   ["Jäähdytys, ostoenergian muutos 1"]
   ["E-luvun muutos 1"]
   ["Toimenpide-ehdotus (fi) 2"]
   ["Toimenpide-ehdotus (sv) 2"]
   ["Lämpö, ostoenergian muutos 2"]
   ["Sähkö, ostoenergian muutos 2"]
   ["Jäähdytys, ostoenergian muutos 2"]
   ["E-luvun muutos 2"]
   ["Toimenpide-ehdotus (fi) 3"]
   ["Toimenpide-ehdotus (sv) 3"]
   ["Lämpö, ostoenergian muutos 3"]
   ["Sähkö, ostoenergian muutos 3"]
   ["Jäähdytys, ostoenergian muutos 3"]
   ["E-luvun muutos 3"]
   ["Suosituksia rakennuksen käyttöön ja ylläpitoon (fi)"]
   ["Suosituksia rakennuksen käyttöön ja ylläpitoon (sv)"]
   ["Lisätietoja energiatehokkuudesta (fi)"]
   ["Lisätietoja energiatehokkuudesta (sv)"]])

(defn fill-headers [sheet style]
  (let [row (xlsx/create-row sheet 0)]
    (.setRowStyle row style)
    (doseq [[idx [label]] (map-indexed vector mappings)]
      (xlsx/create-cell-with-value row idx label))))

(defn fill-row-with-energiatodistus [sheet idx energiatodistus]
  (let [row (xlsx/create-row sheet idx)]
    (xlsx/create-cell-with-value row 0 "Some data 1")
    (xlsx/create-cell-with-value row 1 "Some data 2")))

(defn find-energiatodistus-xlsx [db id]
  (when-let [energiatodistus
             (energiatodistus-service/find-energiatodistus db id)]
    (let [path (->> (java.util.UUID/randomUUID)
                    .toString
                    (format "energiatodistus-%s.xlsx")
                    (str tmp-dir))
          xlsx (xlsx/create-xlsx)
          sheet (xlsx/create-sheet xlsx "Energiatodistus")
          bold-font (xlsx/create-bold-font xlsx)
          bold-style (xlsx/create-style xlsx bold-font)
          _ (fill-headers sheet bold-style)
          _ (fill-row-with-energiatodistus sheet 1 nil)
          _ (fill-row-with-energiatodistus sheet 2 nil)
          _ (io/make-parents path)
          _ (xlsx/save-xlsx xlsx path)
          is (io/input-stream path)]
      (io/delete-file path)
      is)))
