(ns solita.etp.service.energiatodistus-xlsx
  (:require [clojure.java.io :as io]
            [solita.common.xlsx :as xlsx]
            [solita.etp.service.energiatodistus :as energiatodistus-service]))

(def tmp-dir "tmp/")

(def mappings
  [["Todistustunnus" [:id]]
   ["Rakennuksen nimi"[:perustiedot :nimi]]
   ["Rakennustunnus" [:perustiedot :rakennustunnus]]
   ["Kiinteistötunnus" [:perustiedot :kiinteistotunnus]]
   ["Katuosoite suomeksi" [:perustiedot :katuosoite-fi]]
   ["Katuosoite ruotsiksi" [:perustiedot :katuosoite-sv]]
   ["Postinumero" [:perustiedot :postinumero]]
   ["Julkinen rakennus" #(if (-> % :perustiedot :onko-julkinen-rakennus) "Kyllä" "Ei")]
   ["Uudisrakennus" ]
   ["Laatimisvaihe" ]
   ["Havainnointikäynnin päivämäärä" [:perustiedot :havainnointikaynti]]
   ["Rakennuksen osa" [:perustiedot :rakennusosa]]
   ["Rakennuksen valmistumisvuosi" [:perustiedot :valmistumisvuosi]]
   ["Todistuksen laatimispäivä" (fn [_] (str (java.time.LocalDate/now)))]
   ["Viimeinen voimassaolopäivä" (fn [_] (str (.plusYears (java.time.LocalDate/now) 10)))]
   ["Rakennusluokka" ]
   ["Rakennuksen käyttötarkoitusluokka" ]
   ["E-luku" ]
   ["E-luvun vaatimustaso" ]
   ["E-luokka" ]
   ["Keskeiset huomiot (fi)" [:huomiot :teksti-fi]]
   ["Keskeiset huomiot (sv)" [:huomiot :teksti-sv]]
   ["Laatija" [:laatija-fullname]]
   ["Tilaaja" [:perustiedot :tilaaja]]
   ["Tarkastettu viimeksi" ]
   ["Katsottu viimeksi" ]
   ["Lisämerkinnät (fi)" [:lisamerkintoja-fi]]
   ["Lisämerkinnät (sv)" [:lisamerkintoja-sv]]
   ["Tila" ]
   ["Versio" [:versio]]
   ["Lukemattomia viestejä" ]
   ["Yritys" [:perustiedot :yritys :nimi]]
   ["Yrityksen katuosoite" [:perustiedot :yritys :katuosoite]]
   ["Yrityksen postinumero" [:perustiedot :yritys :postinumero]]
   ["Yrityksen postitoimipaikka" [:perustiedot :yritys :postitoimipaikka]]
   ["Laskun numero" ]
   ["Energiatodistuksen kieli" ]
   ["Lämmitetty nettoala" [:lahtotiedot :lammitetty-nettoala]]
   ["Ilmanvuotoluku q_50" [:lahtotiedot :rakennusvaippa :ilmanvuotoluku]]
   ["Ulkoseinät A" [:lahtotiedot :rakennusvaippa :ulkoseinat :ala]]
   ["Ulkoseinät U" [:lahtotiedot :rakennusvaippa :ulkoseinat :U]]
   ["Ulkoseinät U × A" ]
   ["Ulkoseinien osuus lämpöhäviöistä" ]
   ["Yläpohja A" [:lahtotiedot :rakennusvaippa :ylapohja :ala]]
   ["Yläpohja U" [:lahtotiedot :rakennusvaippa :ylapohja :U]]
   ["Yläpohja U × A" ]
   ["Yläpohjan osuus lämpöhäviöistä" ]
   ["Alapohja A" [:lahtotiedot :rakennusvaippa :alapohja :ala]]
   ["Alapohja U" [:lahtotiedot :rakennusvaippa :alapohja :U]]
   ["Alapohja U × A" ]
   ["Alapohjan osuus lämpöhäviöistä" ]
   ["Ikkunat A" [:lahtotiedot :rakennusvaippa :ikkunat :ala]]
   ["Ikkunat U" [:lahtotiedot :rakennusvaippa :ikkunat :U]]
   ["Ikkunat U × A" ]
   ["Ikkunoiden osuus lämpöhäviöistä" ]
   ["Ulko-ovet A" [:lahtotiedot :rakennusvaippa :ulkoovet :ala]]
   ["Ulko-ovet U" [:lahtotiedot :rakennusvaippa :ulkoovet :U]]
   ["Ulko-ovet U × A" ]
   ["Ulko-ovien osuus lämpöhäviöistä" ]
   ["Kylmäsillat A" [:lahtotiedot :rakennusvaippa :kylmasillat-UA :ala]]
   ["Kylmäsillat U" [:lahtotiedot :rakennusvaippa :kylmasillat-UA :U]]
   ["Kylmäsillat U × A" ]
   ["Kylmäsiltojen osuus lämpöhäviöistä" ]
   ["Pohjoinen A" [:lahtotiedot :ikkunat :pohjoinen :ala]]
   ["Pohjoinen U" [:lahtotiedot :ikkunat :pohjoinen :U]]
   ["Pohjoinen g_kohtisuora-arvo" [:lahtotiedot :ikkunat :pohjoinen :g-ks]]
   ["Koillinen A" [:lahtotiedot :ikkunat :koillinen :ala]]
   ["Koillinen U" [:lahtotiedot :ikkunat :koillinen :U]]
   ["Koillinen g_kohtisuora-arvo" [:lahtotiedot :ikkunat :koillinen :g-ks]]
   ["Itä A" [:lahtotiedot :ikkunat :ita :ala]]
   ["Itä U" [:lahtotiedot :ikkunat :ita :U]]
   ["Itä g_kohtisuora-arvo" [:lahtotiedot :ikkunat :ita :g-ks]]
   ["Kaakko A" [:lahtotiedot :ikkunat :kaakko :ala]]
   ["Kaakko U" [:lahtotiedot :ikkunat :kaakko :U]]
   ["Kaakko g_kohtisuora-arvo" [:lahtotiedot :ikkunat :kaakko :g-ks]]
   ["Etelä A" [:lahtotiedot :ikkunat :etela :ala]]
   ["Etelä U" [:lahtotiedot :ikkunat :etela :U]]
   ["Etelä g_kohtisuora-arvo" [:lahtotiedot :ikkunat :etela :g-ks]]
   ["Lounas A" [:lahtotiedot :ikkunat :lounas :ala]]
   ["Lounas U" [:lahtotiedot :ikkunat :lounas :U]]
   ["Lounas g_kohtisuora-arvo" [:lahtotiedot :ikkunat :lounas :g-ks]]
   ["Länsi A" [:lahtotiedot :ikkunat :lansi :ala]]
   ["Länsi U" [:lahtotiedot :ikkunat :lansi :U]]
   ["Länsi g_kohtisuora-arvo" [:lahtotiedot :ikkunat :lansi :g-ks]]
   ["Luode A" [:lahtotiedot :ikkunat :luode :ala]]
   ["Luode U" [:lahtotiedot :ikkunat :luode :U]]
   ["Luode g_kohtisuora-arvo" [:lahtotiedot :ikkunat :luode :g-ks]]
   ["Ilmanvaihtojärjestelmän kuvaus" [:lahtotiedot :ilmanvaihto :kuvaus-fi]]
   ["Ilmanvaihtojärjestelmän kuvaus (sv)" [:lahtotiedot :ilmanvaihto :kuvaus-sv]]
   ["Pääilmanvaihtokoneet, tulo" [:lahtotiedot :ilmanvaihto :paaiv :tulo]]
   ["Pääilmanvaihtokoneet, poisto" [:lahtotiedot :ilmanvaihto :paaiv :poisto]]
   ["Pääilmanvaihtokoneet, järjestelmän SFP-luku" [:lahtotiedot :ilmanvaihto :paaiv :sfp]]
   ["Pääilmanvaihtokoneet, LTO:n lämpötilasuhde" [:lahtotiedot :ilmanvaihto :paaiv :lampotilasuhde]]
   ["Pääilmanvaihtokoneet, jäätymisenesto" [:lahtotiedot :ilmanvaihto :paaiv :jaatymisenesto]]
   ["Erillispoistot, tulo" [:lahtotiedot :ilmanvaihto :erillispoistot :tulo]]
   ["Erillispoistot, poisto" [:lahtotiedot :ilmanvaihto :erillispoistot :poisto]]
   ["Erillispoistot, järjestelmän SFP-luku" [:lahtotiedot :ilmanvaihto :erillispoistot :sfp]]
   ["Ilmanvaihto, tulo" [:lahtotiedot :ilmanvaihto :ivjarjestelma :tulo]]
   ["Ilmanvaihto, poisto" [:lahtotiedot :ilmanvaihto :ivjarjestelma :poisto]]
   ["Järjestelmän SFP-luku" [:lahtotiedot :ilmanvaihto :ivjarjestelma :sfp]]
   ["Rakennuksen ilmanvaihtojärjestelmän LTO:n vuosihyötysuhde:" [:lahtotiedot :ilmanvaihto :lto-vuosihyotysuhde]]
   ["Lämmitysjärjestelmän kuvaus" [:lahtotiedot :lammitys :kuvaus-fi]]
   ["Lämmitysjärjestelmän kuvaus (sv)" [:lahtotiedot :lammitys :kuvaus-sv]]
   ["Tilat: Tuoton hyötysuhde" [:lahtotiedot :lammitys :tilat-ja-iv :tuoton-hyotysuhde]]
   ["Tilat: Jaon ja luovutuksen hyötysuhde" [:lahtotiedot :lammitys :tilat-ja-iv :jaon-hyotysuhde]]
   ["Tilat: Lämpökerroin" [:lahtotiedot :lammitys :tilat-ja-iv :lampokerroin]]
   ["Tilat: Apulaitteiden sähkönkäyttö" [:lahtotiedot :lammitys :tilat-ja-iv :apulaitteet]]
   ["Käyttövesi: Tuoton hyötysuhde" [:lahtotiedot :lammitys :lammin-kayttovesi :tuoton-hyotysuhde]]
   ["Käyttövesi: Jaon ja luovutuksen hyötysuhde" [:lahtotiedot :lammitys :lammin-kayttovesi :jaon-hyotysuhde]]
   ["Käyttövesi: Lämpökerroin" [:lahtotiedot :lammitys :lammin-kayttovesi :lampokerroin]]
   ["Käyttövesi: Apulaitteiden sähkönkäyttö" [:lahtotiedot :lammitys :lammin-kayttovesi :apulaitteet]]
   ["Varaavien tulisijojen määrä" [:lahtotiedot :lammitys :takka :maara]]
   ["Varaavien tulisijojen tuotto" [:lahtotiedot :lammitys :takka :tuotto]]
   ["Ilmalämpöpumppujen määrä" [:lahtotiedot :lammitys :ilmanlampopumppu :maara]]
   ["Ilmalämpöpumppujen tuotto" [:lahtotiedot :lammitys :ilmanlampopumppu :tuotto]]
   ["Jäähdytyskauden painotettu kylmäkerroin" [:lahtotiedot :jaahdytysjarjestelma :jaahdytyskauden-painotettu-kylmakerroin]]
   ["Ominaiskulutus" ]
   ["Lämmitysenergian nettotarve" ]
   ["Selite 1 (fi)" ]
   ["Selite 1 (sv)" ]
   ["Käyttöaste 1" ]
   ["Henkilöt 1" ]
   ["Kuluttajalaitteet 1" ]
   ["Valaistus 1" ]
   ["Selite 2 (fi)" ]
   ["Selite 2 (sv)" ]
   ["Käyttöaste 2" ]
   ["Henkilöt 2" ]
   ["Kuluttajalaitteet 2" ]
   ["Valaistus 2" ]
   ["Selite 3 (fi)" ]
   ["Selite 3 (sv)"  ]
   ["Käyttöaste 3" ]
   ["Henkilöt 3" ]
   ["Kuluttajalaitteet 3" ]
   ["Valaistus 3" ]
   ["Käytettävä energiamuoto 1" ]
   ["Laskettu ostoenergia 1" ]
   ["Kerroin 1" ]
   ["Painotettu vuosikulutus 1" ]
   ["Painotettu neliövuosikulutus 1" ]
   ["Käytettävä energiamuoto 2" ]
   ["Laskettu ostoenergia 2" ]
   ["Kerroin 2" ]
   ["Painotettu vuosikulutus 2" ]
   ["Painotettu neliövuosikulutus 2" ]
   ["Käytettävä energiamuoto 3" ]
   ["Laskettu ostoenergia 3" ]
   ["Kerroin 3" ]
   ["Painotettu vuosikulutus 3" ]
   ["Painotettu neliövuosikulutus 3" ]
   ["Energianlähde 1" ]
   ["Vakioidulla käytöllä laskettu ostoenergia 1"]
   ["Energiamuodon kerroin 1"]
   ["Painotettu vuosikulutus 1"]
   ["Painotettu neliövuosikulutus 1"]
   ["Energianlähde 2"]
   ["Vakioidulla käytöllä laskettu ostoenergia 2"]
   ["Energiamuodon kerroin 2"]
   ["Painotettu vuosikulutus 2"]
   ["Painotettu neliövuosikulutus 2"]
   ["Energianlähde 3"]
   ["Vakioidulla käytöllä laskettu ostoenergia 3"]
   ["Energiamuodon kerroin 3"]
   ["Painotettu vuosikulutus 3"]
   ["Painotettu neliövuosikulutus 3"]
   ["Energianlähde 4"]
   ["Vakioidulla käytöllä laskettu ostoenergia 4"]
   ["Energiamuodon kerroin 4"]
   ["Painotettu vuosikulutus 4"]
   ["Painotettu neliövuosikulutus 4"]
   ["Energianlähde 5"]
   ["Vakioidulla käytöllä laskettu ostoenergia 5"]
   ["Energiamuodon kerroin 5"]
   ["Painotettu vuosikulutus 5"]
   ["Painotettu neliövuosikulutus 5"]
   ["Energiamuoto 1 (fi)"]
   ["Energiamuoto 1 (sv)"]
   ["Vuosikulutus 1"]
   ["Neliövuosikulutus 1"]
   ["Energiamuoto 2 (fi)"]
   ["Energiamuoto 2 (sv)"]
   ["Vuosikulutus 2"]
   ["Neliövuosikulutus 2"]
   ["Energiamuoto 3 (fi)"]
   ["Energiamuoto 3 (sv)"]
   ["Vuosikulutus 3"]
   ["Neliövuosikulutus 3"]
   ["Energiamuoto 4 (fi)"]
   ["Energiamuoto 4 (sv)"]
   ["Vuosikulutus 4"]
   ["Neliövuosikulutus 4"]
   ["Energiamuoto 5 (fi)"]
   ["Energiamuoto 5 (sv)"]
   ["Vuosikulutus 5"]
   ["Neliövuosikulutus 5"]
   ["Energiamuoto 6 (fi)"]
   ["Energiamuoto 6 (sv)"]
   ["Vuosikulutus 6"]
   ["Neliövuosikulutus 6"]
   ["Tilojen lämmitys – Sähkö" ]
   ["Tilojen lämmitys – Lämpö"]
   ["Tuloilman lämmitys – Sähkö"]
   ["Tuloilman lämmitys – Lämpö"]
   ["Käyttöveden valmistus – Sähkö"]
   ["Käyttöveden valmistus – Lämpö"]
   ["Käyttöveden valmistus – Kaukojäähdytys"]
   ["Ilmanvaihto – Sähkö"]
   ["Jäähdytys – Sähkö"]
   ["Jäähdytys – Lämpö"]
   ["Jäähdytys – Kaukojäähdytys"]
   ["Kuluttajalaitteet ja valaistus – Sähkö"]
   ["Yhteensä Sähkö"]
   ["Yhteensä Lämpö"]
   ["Yhteensä Kaukojäähdytys"]
   ["Tilojen lämmitys – Vuosikulutus"]
   ["Tilojen lämmitys – Neliövuosikulutus"]
   ["Ilmanvaihdon lämmitys – Vuosikulutus"]
   ["Ilmanvaihdon lämmitys – Neliövuosikulutus"]
   ["Käyttöveden valmistus – Vuosikulutus"]
   ["Käyttöveden valmistus – Neliövuosikulutus"]
   ["Jäähdytys – Vuosikulutus"]
   ["Jäähdytys – Neliövuosikulutus"]
   ["Aurinko – Vuosikulutus"]
   ["Aurinko – Neliövuosikulutus"]
   ["Ihmiset – Vuosikulutus"]
   ["Ihmiset – Neliövuosikulutus"]
   ["Kuluttajalaitteet – Vuosikulutus"]
   ["Kuluttajalaitteet – Neliövuosikulutus"]
   ["Valaistus – Vuosikulutus"]
   ["Valaistus – Neliövuosikulutus"]
   ["Lämmin käyttövesi – vuosikulutus"]
   ["Lämmin käyttövesi – neliövuosikulutus"]
   ["Laskentatyökalun nimi ja versionumero"]
   ["Ostetun kaukolämpöenergian vuosikulutus"]
   ["Ostetun kaukolämpöenergian neliövuosikulutus"]
   ["Ostetun sähköenergian (kokonaissähkö) vuosikulutus"]
   ["Ostetun sähköenergian (kokonaissähkö) neliövuosikulutus"]
   ["Ostetun sähköenergian (kiinteistö) vuosikulutus"]
   ["Ostetun sähköenergian (kiinteistö) neliövuosikulutus"]
   ["Ostetun sähköenergian (kayttaja) vuosikulutus"]
   ["Ostetun sähköenergian (kayttaja) neliovuosikulutus"]
   ["Ostetun kaukojäähdytysenergian vuosikulutus"]
   ["Ostetun kaukojäähdytysenergian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 1)"]
   ["Ostetun (vapaasti syötettävä 1) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 1) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 2)"]
   ["Ostetun (vapaasti syötettävä 2) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 2) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 3)"]
   ["Ostetun (vapaasti syötettävä 3) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 3) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 4)"]
   ["Ostetun (vapaasti syötettävä 4) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 4) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 5)"]
   ["Ostetun (vapaasti syötettävä 5) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 5) energian neliövuosikulutus"]
   ["Energiamuoto (vapaasti syötettävä 6)"]
   ["Ostetun (vapaasti syötettävä 6) energian vuosikulutus"]
   ["Ostetun (vapaasti syötettävä 6) energian neliövuosikulutus"]
   ["Energianlähde 1"]
   ["polttoaineen määrä vuodessa 1"]
   ["yksikkö 1"]
   ["muunnoskerroin kWh:ksi 1"]
   ["Vuosikulutus 1"]
   ["Neliövuosikulutus 1"]
   ["Energianlähde 2"]
   ["polttoaineen määrä vuodessa 2"]
   ["yksikkö 2"]
   ["muunnoskerroin kWh:ksi 2"]
   ["Vuosikulutus 2"]
   ["Neliövuosikulutus 2"]
   ["Energianlähde 3"]
   ["polttoaineen määrä vuodessa 3"]
   ["yksikkö 3"]
   ["muunnoskerroin kWh:ksi 3"]
   ["Vuosikulutus 3"]
   ["Neliövuosikulutus 3"]
   ["Energianlähde 4"]
   ["polttoaineen määrä vuodessa 4"]
   ["yksikkö 4"]
   ["muunnoskerroin kWh:ksi 4"]
   ["Vuosikulutus 4"]
   ["Neliövuosikulutus 4"]
   ["Energianlähde 5"]
   ["polttoaineen määrä vuodessa 5"]
   ["yksikkö 5"]
   ["muunnoskerroin kWh:ksi 5"]
   ["Vuosikulutus 5"]
   ["Neliövuosikulutus 5"]
   ["Energianlähde 6"]
   ["polttoaineen määrä vuodessa 6"]
   ["yksikkö 6"]
   ["muunnoskerroin kWh:ksi 6"]
   ["Vuosikulutus 6"]
   ["Neliövuosikulutus 6"]
   ["Energianlähde 7"]
   ["polttoaineen määrä vuodessa 7"]
   ["yksikkö 7"]
   ["muunnoskerroin kWh:ksi 7"]
   ["Vuosikulutus 7"]
   ["Neliövuosikulutus 7"]
   ["Energianlähde 8"]
   ["polttoaineen määrä vuodessa 8"]
   ["yksikkö 8"]
   ["muunnoskerroin kWh:ksi 8"]
   ["Vuosikulutus 8"]
   ["Neliövuosikulutus 8"]
   ["Energianlähde 9"]
   ["polttoaineen määrä vuodessa 9"]
   ["yksikkö 9"]
   ["muunnoskerroin kWh:ksi 9"]
   ["Vuosikulutus 9"]
   ["Neliövuosikulutus 9"]
   ["Energianlähde 10"]
   ["polttoaineen määrä vuodessa 10"]
   ["yksikkö 10"]
   ["muunnoskerroin kWh:ksi 10"]
   ["Vuosikulutus 10"]
   ["Neliövuosikulutus 10"]
   ["Energianlähde 11"]
   ["polttoaineen määrä vuodessa 11"]
   ["yksikkö 11"]
   ["muunnoskerroin kWh:ksi 11"]
   ["Vuosikulutus 11"]
   ["Neliövuosikulutus 11"]
   ["Energianlähde 12"]
   ["polttoaineen määrä vuodessa 12"]
   ["yksikkö 12"]
   ["muunnoskerroin kWh:ksi 12"]
   ["Vuosikulutus 12"]
   ["Neliövuosikulutus 12"]
   ["Energianlähde 13"]
   ["polttoaineen määrä vuodessa 13"]
   ["yksikkö 13"]
   ["muunnoskerroin kWh:ksi 13"]
   ["Vuosikulutus 13"]
   ["Neliövuosikulutus 13"]
   ["Energianlähde 14"]
   ["polttoaineen määrä vuodessa 14"]
   ["yksikkö 14"]
   ["muunnoskerroin kWh:ksi 14"]
   ["Vuosikulutus 14"]
   ["Neliövuosikulutus 14"]
   ["Toteutunut sähkön vuosikulutus"]
   ["Toteutunut sähkön neliövuosikulutus"]
   ["Toteutunut kaukolämmön vuosikulutus"]
   ["Toteutunut kaukolämmön neliövuosikulutus"]
   ["Toteutunut polttoaineiden vuosikulutus"]
   ["Toteutunut polttoaineiden neliövuosikulutus"]
   ["Toteutunut kaukojäähdytyksen vuosikulutus"]
   ["Toteutunut kaukojäähdytyksen neliövuosikulutus"]
   ["Toteutunut vuosikulutus yhteensä"]
   ["Toteutunut neliövuosikulutus yhteensä"]
   ["Huomiot ulkoseinät, ulko-ovet ja ikkunat (fi)" [:huomiot :ymparys :teksti-fi]]
   ["Huomiot ulkoseinät, ulko-ovet ja ikkunat (sv)" [:huomiot :ymparys :teksti-sv]]
   ["Toimenpide-ehdotus (fi) 1" [:huomiot :ymparys :toimenpide 0 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 1" [:huomiot :ymparys :toimenpide 0 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 1" [:huomiot :ymparys :toimenpide 0 :lampo]]
   ["Sähkö, ostoenergian muutos 1" [:huomiot :ymparys :toimenpide 0 :sahko]]
   ["Jäähdytys, ostoenergian muutos 1" [:huomiot :ymparys :toimenpide 0 :jaahdytys]]
   ["E-luvun muutos 1" [:huomiot :ymparys :toimenpide 0 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 2" [:huomiot :ymparys :toimenpide 1 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 2" [:huomiot :ymparys :toimenpide 1 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 2" [:huomiot :ymparys :toimenpide 1 :lampo]]
   ["Sähkö, ostoenergian muutos 2" [:huomiot :ymparys :toimenpide 1 :sahko]]
   ["Jäähdytys, ostoenergian muutos 2" [:huomiot :ymparys :toimenpide 1 :jaahdytys]]
   ["E-luvun muutos 2" [:huomiot :ymparys :toimenpide 1 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 3" [:huomiot :ymparys :toimenpide 2 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 3" [:huomiot :ymparys :toimenpide 2 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 3" [:huomiot :ymparys :toimenpide 2 :lampo]]
   ["Sähkö, ostoenergian muutos 3" [:huomiot :ymparys :toimenpide 2 :sahko]]
   ["Jäähdytys, ostoenergian muutos 3" [:huomiot :ymparys :toimenpide 2 :jaahdytys]]
   ["E-luvun muutos 3" [:huomiot :ymparys :toimenpide 2 :eluvun-muutos]]
   ["Huomiot ylä- ja alapohja (fi)" [:huomiot :alapohja-ylapohja :teksti-fi]]
   ["Huomiot ylä- ja alapohja (sv)" [:huomiot :alapohja-ylapohja :teksti-sv]]
   ["Toimenpide-ehdotus (fi) 1" [:huomiot :alapohja-ylapohja :toimenpide 0 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 1" [:huomiot :alapohja-ylapohja :toimenpide 0 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 1" [:huomiot :alapohja-ylapohja :toimenpide 0 :lampo]]
   ["Sähkö, ostoenergian muutos 1" [:huomiot :alapohja-ylapohja :toimenpide 0 :sahko]]
   ["Jäähdytys, ostoenergian muutos 1" [:huomiot :alapohja-ylapohja :toimenpide 0 :jaahdytys]]
   ["E-luvun muutos 1" [:huomiot :alapohja-ylapohja :toimenpide 0 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 2" [:huomiot :alapohja-ylapohja :toimenpide 1 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 2" [:huomiot :alapohja-ylapohja :toimenpide 1 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 2" [:huomiot :alapohja-ylapohja :toimenpide 1 :lampo]]
   ["Sähkö, ostoenergian muutos 2" [:huomiot :alapohja-ylapohja :toimenpide 1 :sahko]]
   ["Jäähdytys, ostoenergian muutos 2" [:huomiot :alapohja-ylapohja :toimenpide 1 :jaahdytys]]
   ["E-luvun muutos 2" [:huomiot :alapohja-ylapohja :toimenpide 1 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 3" [:huomiot :alapohja-ylapohja :toimenpide 2 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 3" [:huomiot :alapohja-ylapohja :toimenpide 2 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 3" [:huomiot :alapohja-ylapohja :toimenpide 2 :lampo]]
   ["Sähkö, ostoenergian muutos 3" [:huomiot :alapohja-ylapohja :toimenpide 2 :sahko]]
   ["Jäähdytys, ostoenergian muutos 3" [:huomiot :alapohja-ylapohja :toimenpide 2 :jaahdytys]]
   ["E-luvun muutos 3" [:huomiot :alapohja-ylapohja :toimenpide 2 :eluvun-muutos]]
   ["Huomiot lämmitys (fi)" [:huomiot :lammitys :teksti-fi]]
   ["Huomiot lämmitys (sv)" [:huomiot :lammitys :teksti-sv]]
   ["Toimenpide-ehdotus (fi) 1" [:huomiot :lammitys :toimenpide 0 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 1" [:huomiot :lammitys :toimenpide 0 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 1" [:huomiot :lammitys :toimenpide 0 :lampo]]
   ["Sähkö, ostoenergian muutos 1" [:huomiot :lammitys :toimenpide 0 :sahko]]
   ["Jäähdytys, ostoenergian muutos 1" [:huomiot :lammitys :toimenpide 0 :jaahdytys]]
   ["E-luvun muutos 1" [:huomiot :lammitys :toimenpide 0 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 2" [:huomiot :lammitys :toimenpide 1 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 2" [:huomiot :lammitys :toimenpide 1 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 2" [:huomiot :lammitys :toimenpide 1 :lampo]]
   ["Sähkö, ostoenergian muutos 2" [:huomiot :lammitys :toimenpide 1 :sahko]]
   ["Jäähdytys, ostoenergian muutos 2" [:huomiot :lammitys :toimenpide 1 :jaahdytys]]
   ["E-luvun muutos 2" [:huomiot :lammitys :toimenpide 1 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 3" [:huomiot :lammitys :toimenpide 2 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 3" [:huomiot :lammitys :toimenpide 2 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 3" [:huomiot :lammitys :toimenpide 2 :lampo]]
   ["Sähkö, ostoenergian muutos 3" [:huomiot :lammitys :toimenpide 2 :sahko]]
   ["Jäähdytys, ostoenergian muutos 3" [:huomiot :lammitys :toimenpide 2 :jaahdytys]]
   ["E-luvun muutos 3" [:huomiot :lammitys :toimenpide 2 :eluvun-muutos]]
   ["Huomiot ilmanvaihto ja ilmastointi (fi)" [:huomiot :iv-ilmastointi :teksti-fi]]
   ["Huomiot ilmanvaihto ja ilmastointi (sv)" [:huomiot :iv-ilmastointi :teksti-sv]]
   ["Toimenpide-ehdotus (fi) 1" [:huomiot :iv-ilmastointi :toimenpide 0 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 1" [:huomiot :iv-ilmastointi :toimenpide 0 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 1" [:huomiot :iv-ilmastointi :toimenpide 0 :lampo]]
   ["Sähkö, ostoenergian muutos 1" [:huomiot :iv-ilmastointi :toimenpide 0 :sahko]]
   ["Jäähdytys, ostoenergian muutos 1" [:huomiot :iv-ilmastointi :toimenpide 0 :jaahdytys]]
   ["E-luvun muutos 1" [:huomiot :iv-ilmastointi :toimenpide 0 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 2" [:huomiot :iv-ilmastointi :toimenpide 1 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 2" [:huomiot :iv-ilmastointi :toimenpide 1 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 2" [:huomiot :iv-ilmastointi :toimenpide 1 :lampo]]
   ["Sähkö, ostoenergian muutos 2" [:huomiot :iv-ilmastointi :toimenpide 1 :sahko]]
   ["Jäähdytys, ostoenergian muutos 2" [:huomiot :iv-ilmastointi :toimenpide 1 :jaahdytys]]
   ["E-luvun muutos 2" [:huomiot :iv-ilmastointi :toimenpide 1 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 3" [:huomiot :iv-ilmastointi :toimenpide 2 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 3" [:huomiot :iv-ilmastointi :toimenpide 2 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 3" [:huomiot :iv-ilmastointi :toimenpide 2 :lampo]]
   ["Sähkö, ostoenergian muutos 3" [:huomiot :iv-ilmastointi :toimenpide 2 :sahko]]
   ["Jäähdytys, ostoenergian muutos 3" [:huomiot :iv-ilmastointi :toimenpide 2 :jaahdytys]]
   ["E-luvun muutos 3" [:huomiot :iv-ilmastointi :toimenpide 2 :eluvun-muutos]]
   ["Huomiot valaistus ja muut järjestelmät (fi)" [:huomiot :valaistus-muut :teksti-fi]]
   ["Huomiot valaistus ja muut järjestelmät (sv)" [:huomiot :valaistus-muut :teksti-sv]]
   ["Toimenpide-ehdotus (fi) 1" [:huomiot :valaistus-muut :toimenpide 0 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 1" [:huomiot :valaistus-muut :toimenpide 0 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 1" [:huomiot :valaistus-muut :toimenpide 0 :lampo]]
   ["Sähkö, ostoenergian muutos 1" [:huomiot :valaistus-muut :toimenpide 0 :sahko]]
   ["Jäähdytys, ostoenergian muutos 1" [:huomiot :valaistus-muut :toimenpide 0 :jaahdytys]]
   ["E-luvun muutos 1" [:huomiot :valaistus-muut :toimenpide 0 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 2" [:huomiot :valaistus-muut :toimenpide 1 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 2" [:huomiot :valaistus-muut :toimenpide 1 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 2" [:huomiot :valaistus-muut :toimenpide 1 :lampo]]
   ["Sähkö, ostoenergian muutos 2" [:huomiot :valaistus-muut :toimenpide 1 :sahko]]
   ["Jäähdytys, ostoenergian muutos 2" [:huomiot :valaistus-muut :toimenpide 1 :jaahdytys]]
   ["E-luvun muutos 2" [:huomiot :valaistus-muut :toimenpide 1 :eluvun-muutos]]
   ["Toimenpide-ehdotus (fi) 3" [:huomiot :valaistus-muut :toimenpide 2 :nimi-fi]]
   ["Toimenpide-ehdotus (sv) 3" [:huomiot :valaistus-muut :toimenpide 2 :nimi-sv]]
   ["Lämpö, ostoenergian muutos 3" [:huomiot :valaistus-muut :toimenpide 2 :lampo]]
   ["Sähkö, ostoenergian muutos 3" [:huomiot :valaistus-muut :toimenpide 2 :sahko]]
   ["Jäähdytys, ostoenergian muutos 3" [:huomiot :valaistus-muut :toimenpide 2 :jaahdytys]]
   ["E-luvun muutos 3" [:huomiot :valaistus-muut :toimenpide 2 :eluvun-muutos]]
   ["Suosituksia rakennuksen käyttöön ja ylläpitoon (fi)" [:perustiedot :keskeiset-suositukset-fi]]
   ["Suosituksia rakennuksen käyttöön ja ylläpitoon (sv)" [:perustiedot :keskeiset-suositukset-sv]]
   ["Lisätietoja energiatehokkuudesta (fi)"]
   ["Lisätietoja energiatehokkuudesta (sv)"]])

(def indexed-mappings (map-indexed vector mappings))

(defn fill-headers [sheet style]
  (let [row (xlsx/create-row sheet 0)]
    (.setRowStyle row style)
    (doseq [[idx [label]] indexed-mappings]
      (xlsx/create-cell-with-value row idx label))))

(defn v-from-energiatodistus [energiatodistus cursor-or-f]
  (cond
    (nil? cursor-or-f)
    "Vaatii speksausta tai selvitystä"

    (vector? cursor-or-f)
    (get-in energiatodistus cursor-or-f)

    :else
    (cursor-or-f energiatodistus)))

(defn fill-row-with-energiatodistus [sheet idx energiatodistus]
  (let [row (xlsx/create-row sheet idx)]
    (doseq [[idx [_ cursor-or-f]] indexed-mappings]
      (xlsx/create-cell-with-value
       row
       idx
       (v-from-energiatodistus energiatodistus cursor-or-f)))))

(defn find-laatija-energiatodistukset-xlsx [db laatija-id]
  (when-let [energiatodistukset
             (energiatodistus-service/find-energiatodistukset-by-laatija
              db
              laatija-id
              nil)]
    (let [path (->> (java.util.UUID/randomUUID)
                    .toString
                    (format "energiatodistus-%s.xlsx")
                    (str tmp-dir))
          xlsx (xlsx/create-xlsx)
          sheet (xlsx/create-sheet xlsx "Energiatodistus")
          bold-font (xlsx/create-bold-font xlsx)
          bold-style (xlsx/create-style xlsx bold-font)]
      (fill-headers sheet bold-style)
      (doseq [[idx energiatodistus] (map-indexed vector energiatodistukset)]
        (fill-row-with-energiatodistus sheet (inc idx) energiatodistus))
      (io/make-parents path)
      (xlsx/save-xlsx xlsx path)
      (let [is (io/input-stream path)]
        (io/delete-file path)
        is))))
