create table vk_note (
  id int generated by default as identity primary key,
  valvonta_id int not null references etp.vk_valvonta (id),
  deleted boolean not null default false,
  description text not null
);

call audit.activate('vk_note'::name);