create table viesti_liite (
  id int generated by default as identity primary key,
  viestiketju_id int not null references viestiketju (id),
  nimi text,
  contenttype text,
  url text,
  deleted boolean not null default false
);

call audit.activate('viesti_liite'::name);