create table liite (
  id int generated by default as identity primary key,
  createtime timestamp with time zone not null default now(),
  createdby_id int not null references kayttaja (id),
  energiatodistus_id int not null references energiatodistus (id),
  nimi text,
  contenttype text,
  url text
);
