create table liite (
  id int generated by default as identity primary key,
  energiatodistus_id int not null references energiatodistus (id),
  nimi text,
  contenttype text,
  url text,
  deleted boolean not null default false
);

call audit.activate('liite'::name);
