create table liite (
  id int generated by default as identity primary key,
  energiatodistus_id int not null references energiatodistus (id),
  nimi text,
  contenttype text,
  url text
);

call audit.create_audit_table('liite'::name);
call audit.activate('liite'::name);
