create table laatija (
  id int generated by default as identity primary key,
  kayttaja int REFERENCES kayttaja (id) NOT NULL UNIQUE,
  henkilotunnus text NOT NULL,
  patevyystaso int NOT NULL,
  toteamispaivamaara date NOT NULL,
  toteaja text NOT NULL,
  laatimiskielto boolean NOT NULL DEFAULT false,
  toimintaalue int,
  muut_toimintaalueet int[] NOT NULL DEFAULT '{}',
  julkinen_puhelin boolean NOT NULL DEFAULT false,
  julkinen_email boolean NOT NULL DEFAULT false,
  julkinen_osoite boolean NOT NULL DEFAULT false,
  jakeluosoite text NOT NULL,
  postinumero text NOT NULL,
  postitoimipaikka text NOT NULL,
  maa char(2) REFERENCES country (id) NOT NULL DEFAULT 'FI'
);
