create table yritys (
  id int generated by default as identity primary key,
  ytunnus text unique,
  nimi text NOT NULL,
  verkkolaskuosoite text,
  jakeluosoite text NOT NULL,
  postinumero text NOT NULL,
  postitoimipaikka text NOT NULL,
  maa char(2) REFERENCES country (id) NOT NULL DEFAULT 'FI'
);
