
create table energiatodistus (
  id int generated by default as identity primary key,
  versio int not null,
  allekirjoituksessaaika timestamp,
  allekirjoitusaika timestamp,
  laatija_id int not null references laatija (id),
  data jsonb
);
