CREATE TYPE energiatodistus_tila AS ENUM (
  'luonnos', 'valmis'
);

create table energiatodistus (
  id int generated by default as identity primary key,
  tila energiatodistus_tila default 'luonnos',
  data jsonb
);
