
insert into country (id, alpha3, numeric, name, label_fi, label_sv)
values
('AD', 'AND', 20, 'Andorra', 'Andorra', 'Andorra'),
('AE', 'ARE', 784, 'United Arab Emirates', 'Yhdistyneet arabiemiirikunnat', 'Förenade Arabemiraten'),
('AF', 'AFG', 4, 'Afghanistan', 'Afganistan', 'Afghanistan'),
('AG', 'ATG', 28, 'Antigua and Barbuda', 'Antigua ja Barbuda', 'Antigua och Barbuda'),
('AI', 'AIA', 660, 'Anguilla', null, null),
('AL', 'ALB', 8, 'Albania', 'Albania', 'Albanien'),
('AM', 'ARM', 51, 'Armenia', 'Armenia', 'Armenien'),
('AN', 'ANT', 530, 'Netherlands Antilles', null, null),
('AO', 'AGO', 24, 'Angola', 'Angola', 'Angola'),
('AQ', 'ATA', 10, 'Antarctica', null, null),
('AR', 'ARG', 32, 'Argentina', 'Argentiina', 'Argentina'),
('AS', 'ASM', 16, 'American Samoa', null, null),
('AT', 'AUT', 40, 'Austria', 'Itävalta', 'Österrike'),
('AU', 'AUS', 36, 'Australia', 'Australia', 'Australien'),
('AW', 'ABW', 533, 'Aruba', null, null),
('AX', 'ALA', 248, 'Åland', null, null),
('AZ', 'AZE', 31, 'Azerbaijan', 'Azerbaidžan', 'Azerbajdzjan'),
('BA', 'BIH', 70, 'Bosnia and Herzegovina', 'Bosnia ja Hertsegovina', 'Bosnien och Hercegovina'),
('BB', 'BRB', 52, 'Barbados', 'Barbados', 'Barbados'),
('BD', 'BGD', 50, 'Bangladesh', 'Bangladesh', 'Bangladesh'),
('BE', 'BEL', 56, 'Belgium', 'Belgia', 'Belgien'),
('BF', 'BFA', 854, 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'),
('BG', 'BGR', 100, 'Bulgaria', 'Bulgaria', 'Bulgarien'),
('BH', 'BHR', 48, 'Bahrain', 'Bahrain', 'Bahrain'),
('BI', 'BDI', 108, 'Burundi', 'Burundi', 'Burundi'),
('BJ', 'BEN', 204, 'Benin', 'Benin', 'Benin'),
('BL', 'BLM', 652, 'Saint Barthélemy', null, null),
('BM', 'BMU', 60, 'Bermuda', null, null),
('BN', 'BRN', 96, 'Brunei', 'Brunei', 'Brunei'),
('BO', 'BOL', 68, 'Bolivia', 'Bolivia', 'Bolivia'),
('BQ', 'BES', 535, 'Bonaire, Sint Eustatius, and Saba', null, null),
('BR', 'BRA', 76, 'Brazil', 'Brasilia', 'Brasilien'),
('BS', 'BHS', 44, 'Bahamas', 'Bahama', 'Bahamas'),
('BT', 'BTN', 64, 'Bhutan', 'Bhutan', 'Bhutan'),
('BV', 'BVT', 74, 'Bouvet Island', null, null),
('BW', 'BWA', 72, 'Botswana', 'Botswana', 'Botswana'),
('BY', 'BLR', 112, 'Belarus', 'Valko-Venäjä', 'Vitryssland'),
('BZ', 'BLZ', 84, 'Belize', 'Belize', 'Belize'),
('CA', 'CAN', 124, 'Canada', 'Kanada', 'Kanada'),
('CC', 'CCK', 166, 'Cocos [Keeling] Islands', null, null),
('CD', 'COD', 180, 'DR Congo', null, null),
('CF', 'CAF', 140, 'Central African Republic', 'Keski-Afrikan tasavalta', 'Centralafrikanska republiken'),
('CG', 'COG', 178, 'Congo Republic', null, null),
('CH', 'CHE', 756, 'Switzerland', 'Sveitsi', 'Schweiz'),
('CI', 'CIV', 384, 'Ivory Coast', 'Norsunluurannikko', 'Elfenbenskusten'),
('CK', 'COK', 184, 'Cook Islands', null, null),
('CL', 'CHL', 152, 'Chile', 'Chile', 'Chile'),
('CM', 'CMR', 120, 'Cameroon', 'Kamerun', 'Kamerun'),
('CN', 'CHN', 156, 'China', 'Kiina', 'Kina'),
('CO', 'COL', 170, 'Colombia', 'Kolumbia', 'Colombia'),
('CR', 'CRI', 188, 'Costa Rica', 'Costa Rica', 'Costa Rica'),
('CS', 'SCG', 891, 'Serbia and Montenegro', null, null),
('CU', 'CUB', 192, 'Cuba', 'Kuuba', 'Kuba'),
('CV', 'CPV', 132, 'Cabo Verde', null, null),
('CW', 'CUW', 531, 'Curaçao', null, null),
('CX', 'CXR', 162, 'Christmas Island', null, null),
('CY', 'CYP', 196, 'Cyprus', 'Kypros', 'Cypern'),
('CZ', 'CZE', 203, 'Czechia', 'Tšekki', 'Tjeckien'),
('DE', 'DEU', 276, 'Germany', 'Saksa', 'Tyskland'),
('DJ', 'DJI', 262, 'Djibouti', 'Djibouti', 'Djibouti'),
('DK', 'DNK', 208, 'Denmark', 'Tanska', 'Danmark'),
('DM', 'DMA', 212, 'Dominica', 'Dominica', 'Dominica'),
('DO', 'DOM', 214, 'Dominican Republic', 'Dominikaaninen tasavalta', 'Dominikanska republiken'),
('DZ', 'DZA', 12, 'Algeria', 'Algeria', 'Algeriet'),
('EC', 'ECU', 218, 'Ecuador', 'Ecuador', 'Ecuador'),
('EE', 'EST', 233, 'Estonia', 'Viro', 'Estland'),
('EG', 'EGY', 818, 'Egypt', 'Egypti', 'Egypten'),
('EH', 'ESH', 732, 'Western Sahara', null, null),
('ER', 'ERI', 232, 'Eritrea', 'Eritrea', 'Eritrea'),
('ES', 'ESP', 724, 'Spain', 'Espanja', 'Spanien'),
('ET', 'ETH', 231, 'Ethiopia', 'Etiopia', 'Etiopien'),
('FI', 'FIN', 246, 'Finland', 'Suomi', 'Finland'),
('FJ', 'FJI', 242, 'Fiji', 'Fidži', 'Fiji'),
('FK', 'FLK', 238, 'Falkland Islands', null, null),
('FM', 'FSM', 583, 'Micronesia', 'Mikronesia', 'Mikronesien'),
('FO', 'FRO', 234, 'Faroe Islands', null, null),
('FR', 'FRA', 250, 'France', 'Ranska', 'Frankrike'),
('GA', 'GAB', 266, 'Gabon', 'Gabon', 'Gabon'),
('GB', 'GBR', 826, 'United Kingdom', 'Yhdistynyt kuningaskunta', 'Storbritannien'),
('GD', 'GRD', 308, 'Grenada', 'Grenada', 'Grenada'),
('GE', 'GEO', 268, 'Georgia', 'Georgia', 'Georgien'),
('GF', 'GUF', 254, 'French Guiana', null, null),
('GG', 'GGY', 831, 'Guernsey', null, null),
('GH', 'GHA', 288, 'Ghana', 'Ghana', 'Ghana'),
('GI', 'GIB', 292, 'Gibraltar', null, null),
('GL', 'GRL', 304, 'Greenland', null, null),
('GM', 'GMB', 270, 'Gambia', 'Gambia', 'Gambia'),
('GN', 'GIN', 324, 'Guinea', 'Guinea', 'Guinea'),
('GP', 'GLP', 312, 'Guadeloupe', null, null),
('GQ', 'GNQ', 226, 'Equatorial Guinea', 'Päiväntasaajan Guinea', 'Ekvatorialguinea'),
('GR', 'GRC', 300, 'Greece', 'Kreikka', 'Grekland'),
('GS', 'SGS', 239, 'South Georgia and South Sandwich Islands', null, null),
('GT', 'GTM', 320, 'Guatemala', 'Guatemala', 'Guatemala'),
('GU', 'GUM', 316, 'Guam', null, null),
('GW', 'GNB', 624, 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau'),
('GY', 'GUY', 328, 'Guyana', 'Guyana', 'Guyana'),
('HK', 'HKG', 344, 'Hong Kong', null, null),
('HM', 'HMD', 334, 'Heard Island and McDonald Islands', null, null),
('HN', 'HND', 340, 'Honduras', 'Honduras', 'Honduras'),
('HR', 'HRV', 191, 'Croatia', 'Kroatia', 'Kroatien'),
('HT', 'HTI', 332, 'Haiti', 'Haiti', 'Haiti'),
('HU', 'HUN', 348, 'Hungary', 'Unkari', 'Ungern'),
('ID', 'IDN', 360, 'Indonesia', 'Indonesia', 'Indonesien'),
('IE', 'IRL', 372, 'Ireland', 'Irlanti', 'Irland'),
('IL', 'ISR', 376, 'Israel', 'Israel', 'Israel'),
('IM', 'IMN', 833, 'Isle of Man', null, null),
('IN', 'IND', 356, 'India', 'Intia', 'Indien'),
('IO', 'IOT', 86, 'British Indian Ocean Territory', null, null),
('IQ', 'IRQ', 368, 'Iraq', 'Irak', 'Irak'),
('IR', 'IRN', 364, 'Iran', 'Iran', 'Iran'),
('IS', 'ISL', 352, 'Iceland', 'Islanti', 'Island'),
('IT', 'ITA', 380, 'Italy', 'Italia', 'Italien'),
('JE', 'JEY', 832, 'Jersey', null, null),
('JM', 'JAM', 388, 'Jamaica', 'Jamaika', 'Jamaica'),
('JO', 'JOR', 400, 'Jordan', 'Jordan', 'Jordan'),
('JP', 'JPN', 392, 'Japan', 'Japani', 'Japan'),
('KE', 'KEN', 404, 'Kenya', 'Kenia', 'Kenya'),
('KG', 'KGZ', 417, 'Kyrgyzstan', 'Kirgisia', 'Kirgizistan'),
('KH', 'KHM', 116, 'Cambodia', 'Kambodža', 'Kambodja'),
('KI', 'KIR', 296, 'Kiribati', 'Kiribati', 'Kiribati'),
('KM', 'COM', 174, 'Comoros', 'Komorit', 'Komorerna'),
('KN', 'KNA', 659, 'St Kitts and Nevis', null, null),
('KP', 'PRK', 408, 'North Korea', 'Pohjois-Korea', 'Nordkorea'),
('KR', 'KOR', 410, 'South Korea', 'Etelä-Korea', 'Sydkorea'),
('KW', 'KWT', 414, 'Kuwait', 'Kuwait', 'Kuwait'),
('KY', 'CYM', 136, 'Cayman Islands', null, null),
('KZ', 'KAZ', 398, 'Kazakhstan', 'Kazakstan', 'Kazakstan'),
('LA', 'LAO', 418, 'Laos', 'Laos', 'Laos'),
('LB', 'LBN', 422, 'Lebanon', 'Libanon', 'Libanon'),
('LC', 'LCA', 662, 'Saint Lucia', 'Saint Lucia', 'Saint Lucia'),
('LI', 'LIE', 438, 'Liechtenstein', 'Liechtenstein', 'Liechtenstein'),
('LK', 'LKA', 144, 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
('LR', 'LBR', 430, 'Liberia', 'Liberia', 'Liberia'),
('LS', 'LSO', 426, 'Lesotho', 'Lesotho', 'Lesotho'),
('LT', 'LTU', 440, 'Lithuania', 'Liettua', 'Litauen'),
('LU', 'LUX', 442, 'Luxembourg', 'Luxemburg', 'Luxemburg'),
('LV', 'LVA', 428, 'Latvia', 'Latvia', 'Lettland'),
('LY', 'LBY', 434, 'Libya', 'Libya', 'Libyen'),
('MA', 'MAR', 504, 'Morocco', 'Marokko', 'Marocko'),
('MC', 'MCO', 492, 'Monaco', 'Monaco', 'Monaco'),
('MD', 'MDA', 498, 'Moldova', 'Moldova', 'Moldavien'),
('ME', 'MNE', 499, 'Montenegro', 'Montenegro', 'Montenegro'),
('MF', 'MAF', 663, 'Saint Martin', null, null),
('MG', 'MDG', 450, 'Madagascar', 'Madagaskar', 'Madagaskar'),
('MH', 'MHL', 584, 'Marshall Islands', 'Marshallinsaaret', 'Marshallöarna'),
('MK', 'MKD', 807, 'North Macedonia', null, null),
('ML', 'MLI', 466, 'Mali', 'Mali', 'Mali'),
('MM', 'MMR', 104, 'Myanmar', 'Myanmar', 'Burma'),
('MN', 'MNG', 496, 'Mongolia', 'Mongolia', 'Mongoliet'),
('MO', 'MAC', 446, 'Macao', null, null),
('MP', 'MNP', 580, 'Northern Mariana Islands', null, null),
('MQ', 'MTQ', 474, 'Martinique', null, null),
('MR', 'MRT', 478, 'Mauritania', 'Mauritania', 'Mauretanien'),
('MS', 'MSR', 500, 'Montserrat', null, null),
('MT', 'MLT', 470, 'Malta', 'Malta', 'Malta'),
('MU', 'MUS', 480, 'Mauritius', 'Mauritius', 'Mauritius'),
('MV', 'MDV', 462, 'Maldives', 'Malediivit', 'Maldiverna'),
('MW', 'MWI', 454, 'Malawi', 'Malawi', 'Malawi'),
('MX', 'MEX', 484, 'Mexico', 'Meksiko', 'Mexiko'),
('MY', 'MYS', 458, 'Malaysia', 'Malesia', 'Malaysia'),
('MZ', 'MOZ', 508, 'Mozambique', 'Mosambik', 'Moçambique'),
('NA', 'NAM', 516, 'Namibia', 'Namibia', 'Namibia'),
('NC', 'NCL', 540, 'New Caledonia', null, null),
('NE', 'NER', 562, 'Niger', 'Niger', 'Niger'),
('NF', 'NFK', 574, 'Norfolk Island', null, null),
('NG', 'NGA', 566, 'Nigeria', 'Nigeria', 'Nigeria'),
('NI', 'NIC', 558, 'Nicaragua', 'Nicaragua', 'Nicaragua'),
('NL', 'NLD', 528, 'Netherlands', 'Alankomaat', 'Nederländerna'),
('NO', 'NOR', 578, 'Norway', 'Norja', 'Norge'),
('NP', 'NPL', 524, 'Nepal', 'Nepal', 'Nepal'),
('NR', 'NRU', 520, 'Nauru', 'Nauru', 'Nauru'),
('NU', 'NIU', 570, 'Niue', null, null),
('NZ', 'NZL', 554, 'New Zealand', 'Uusi-Seelanti', 'Nya Zeeland'),
('OM', 'OMN', 512, 'Oman', 'Oman', 'Oman'),
('PA', 'PAN', 591, 'Panama', 'Panama', 'Panama'),
('PE', 'PER', 604, 'Peru', 'Peru', 'Peru'),
('PF', 'PYF', 258, 'French Polynesia', null, null),
('PG', 'PNG', 598, 'Papua New Guinea', 'Papua-Uusi-Guinea', 'Papua Nya Guinea'),
('PH', 'PHL', 608, 'Philippines', 'Filippiinit', 'Filippinerna'),
('PK', 'PAK', 586, 'Pakistan', 'Pakistan', 'Pakistan'),
('PL', 'POL', 616, 'Poland', 'Puola', 'Polen'),
('PM', 'SPM', 666, 'Saint Pierre and Miquelon', null, null),
('PN', 'PCN', 612, 'Pitcairn Islands', null, null),
('PR', 'PRI', 630, 'Puerto Rico', 'Puerto Rico', 'Puerto Rico'),
('PS', 'PSE', 275, 'Palestine', null, null),
('PT', 'PRT', 620, 'Portugal', 'Portugali', 'Portugal'),
('PW', 'PLW', 585, 'Palau', 'Palau', 'Palau'),
('PY', 'PRY', 600, 'Paraguay', 'Paraguay', 'Paraguay'),
('QA', 'QAT', 634, 'Qatar', 'Qatar', 'Qatar'),
('RE', 'REU', 638, 'Réunion', null, null),
('RO', 'ROU', 642, 'Romania', 'Romania', 'Rumänien'),
('RS', 'SRB', 688, 'Serbia', 'Serbia', 'Serbien'),
('RU', 'RUS', 643, 'Russia', 'Venäjä', 'Ryssland'),
('RW', 'RWA', 646, 'Rwanda', 'Ruanda', 'Rwanda'),
('SA', 'SAU', 682, 'Saudi Arabia', 'Saudi-Arabia', 'Saudiarabien'),
('SB', 'SLB', 90, 'Solomon Islands', 'Salomonsaaret', 'Salomonöarna'),
('SC', 'SYC', 690, 'Seychelles', 'Seychellit', 'Seychellerna'),
('SD', 'SDN', 729, 'Sudan', 'Sudan', 'Sudan'),
('SE', 'SWE', 752, 'Sweden', 'Ruotsi', 'Sverige'),
('SG', 'SGP', 702, 'Singapore', 'Singapore', 'Singapore'),
('SH', 'SHN', 654, 'Saint Helena', null, null),
('SI', 'SVN', 705, 'Slovenia', 'Slovenia', 'Slovenien'),
('SJ', 'SJM', 744, 'Svalbard and Jan Mayen', null, null),
('SK', 'SVK', 703, 'Slovakia', 'Slovakia', 'Slovakien'),
('SL', 'SLE', 694, 'Sierra Leone', 'Sierra Leone', 'Sierra Leone'),
('SM', 'SMR', 674, 'San Marino', 'San Marino', 'San Marino'),
('SN', 'SEN', 686, 'Senegal', 'Senegal', 'Senegal'),
('SO', 'SOM', 706, 'Somalia', 'Somalia', 'Somalia'),
('SR', 'SUR', 740, 'Suriname', 'Suriname', 'Surinam'),
('SS', 'SSD', 728, 'South Sudan', 'Etelä-Sudan', 'Sydsudan'),
('ST', 'STP', 678, 'São Tomé and Príncipe', null, null),
('SV', 'SLV', 222, 'El Salvador', 'El Salvador', 'El Salvador'),
('SX', 'SXM', 534, 'Sint Maarten', null, null),
('SY', 'SYR', 760, 'Syria', 'Syyria', 'Syrien'),
('SZ', 'SWZ', 748, 'Eswatini', null, null),
('TC', 'TCA', 796, 'Turks and Caicos Islands', null, null),
('TD', 'TCD', 148, 'Chad', 'Tšad', 'Tchad'),
('TF', 'ATF', 260, 'French Southern Territories', null, null),
('TG', 'TGO', 768, 'Togo', 'Togo', 'Togo'),
('TH', 'THA', 764, 'Thailand', 'Thaimaa', 'Thailand'),
('TJ', 'TJK', 762, 'Tajikistan', 'Tadžikistan', 'Tadzjikistan'),
('TK', 'TKL', 772, 'Tokelau', null, null),
('TL', 'TLS', 626, 'Timor-Leste', null, null),
('TM', 'TKM', 795, 'Turkmenistan', 'Turkmenistan', 'Turkmenistan'),
('TN', 'TUN', 788, 'Tunisia', 'Tunisia', 'Tunisien'),
('TO', 'TON', 776, 'Tonga', 'Tonga', 'Tonga'),
('TR', 'TUR', 792, 'Turkey', 'Turkki', 'Turkiet'),
('TT', 'TTO', 780, 'Trinidad and Tobago', 'Trinidad ja Tobago', 'Trinidad och Tobago'),
('TV', 'TUV', 798, 'Tuvalu', 'Tuvalu', 'Tuvalu'),
('TW', 'TWN', 158, 'Taiwan', null, null),
('TZ', 'TZA', 834, 'Tanzania', 'Tansania', 'Tanzania'),
('UA', 'UKR', 804, 'Ukraine', 'Ukraina', 'Ukraina'),
('UG', 'UGA', 800, 'Uganda', 'Uganda', 'Uganda'),
('UM', 'UMI', 581, 'U.S. Minor Outlying Islands', null, null),
('US', 'USA', 840, 'United States', 'Yhdysvallat', 'Förenta Staterna'),
('UY', 'URY', 858, 'Uruguay', 'Uruguay', 'Uruguay'),
('UZ', 'UZB', 860, 'Uzbekistan', 'Uzbekistan', 'Uzbekistan'),
('VA', 'VAT', 336, 'Vatican City', null, null),
('VC', 'VCT', 670, 'St Vincent and Grenadines', null, null),
('VE', 'VEN', 862, 'Venezuela', 'Venezuela', 'Venezuela'),
('VG', 'VGB', 92, 'British Virgin Islands', null, null),
('VI', 'VIR', 850, 'U.S. Virgin Islands', null, null),
('VN', 'VNM', 704, 'Vietnam', 'Vietnam', 'Vietnam'),
('VU', 'VUT', 548, 'Vanuatu', 'Vanuatu', 'Vanuatu'),
('WF', 'WLF', 876, 'Wallis and Futuna', null, null),
('WS', 'WSM', 882, 'Samoa', 'Samoa', 'Samoa'),
('XK', 'XKX', 0, 'Kosovo', 'Kosovo', 'Kosovo'),
('YE', 'YEM', 887, 'Yemen', 'Jemen', 'Jemen'),
('YT', 'MYT', 175, 'Mayotte', null, null),
('ZA', 'ZAF', 710, 'South Africa', 'Etelä-Afrikka', 'Sydafrika'),
('ZM', 'ZMB', 894, 'Zambia', 'Sambia', 'Zambia'),
('ZW', 'ZWE', 716, 'Zimbabwe', 'Zimbabwe', 'Zimbabwe')
on conflict (id) do update
  set alpha3 = excluded.alpha3,
      name = excluded.name,
      label_fi = excluded.label_fi,
      label_sv = excluded.label_sv;