
insert into kayttotarkoitusluokka (id, versio, label_fi, label_sv, ordinal, deleted)
values
(1, 2013, 'Erilliset pientalot', 'Fristående småhus', 1, false),
(2, 2013, 'Rivi- ja ketjutalot', 'Rad- och kedjehus', 2, false),
(3, 2013, 'Asuinkerrostalot', 'Flervåningsbostadshus', 3, false),
(4, 2013, 'Toimistorakennukset', 'Kontorsbyggnader', 4, false),
(5, 2013, 'Liikerakennukset', 'Affärsbyggnader', 5, false),
(6, 2013, 'Majoitusliikerakennukset', 'Byggnader för inkvarteringsanläggningar', 6, false),
(7, 2013, 'Opetusrakennukset ja päiväkodit', 'Undervisningsbyggnader och daghem', 7, false),
(8, 2013, 'Liikuntahallit pois lukien uima- ja jäähallit', 'Idrottshallar (med undantag av simhallar och ishallar)', 8, false),
(9, 2013, 'Sairaalat', 'Sjukhus', 9, false),
(10, 2013, 'Liikuntahallit, uimahallit, jäähallit, liikenteen rakennukset', 'Idrottshallar, simhallar, ishallar, byggnader för trafik', 10, false),
(11, 2013, 'Varastorakennukset ja erilliset moottoriajoneuvosuojat', 'Lagerbyggnader och fristående utrymmen för motorfordon', 11, false),

(1, 2018, '1. Pienet asuinrakennukset', 'Små bostadsbyggnader', 1, false),
(2, 2018, '2. Asuinkerrostalot', 'Flervåningsbostadshus', 2, false),
(3, 2018, '3. Toimistorakennukset', 'Kontorsbyggnader', 3, false),
(4, 2018, '4. Liikerakennukset', 'Affärsbyggnader', 4, false),
(5, 2018, '5. Majoitusliikerakennukset', 'Byggnader för inkvarteringsanläggningar', 5, false),
(6, 2018, '6. Opetusrakennukset ja päiväkodit', 'Undervisningsbyggnader och daghem', 6, false),
(7, 2018, '7. Liikuntahallit, lukuun ottamatta uimahalleja ja jäähalleja', 'Idrottshallar, med undantag för simhallar och ishallar', 7, false),
(8, 2018, '8. Sairaalat', 'Sjukhus', 8, false),
(9, 2018, '9. Muut rakennukset', 'Övriga byggnader', 9, false)

on conflict (id, versio) do update
  set label_fi = excluded.label_fi,
      label_sv = excluded.label_sv,
      deleted = excluded.deleted;


insert into alakayttotarkoitusluokka (id, versio, kayttotarkoitusluokka_id, label_fi, label_sv, deleted)
values
('YAT', 2013, 1, 'Yhden asunnon talot', 'Hus med en bostad', false),
('KAT', 2013, 1, 'Kahden asunnon talot', 'Hus med två bostäder', false),
('MEP', 2013, 1, 'Muut erilliset pientalot', 'Övriga fristående småhus', false),
('MAEP', 2013, 1, 'Majoituselinkeinon harjoittamiseen tarkoitetut loma-asunnot, jotka ovat erillisiä pientaloja', 'Fritidshus avsedda för kommersiell logiverksamhet som är fristående småhus', false),
('RK', 2013, 2, 'Rivi- ja ketjutalot', 'Rad- och kedjehus', false),
('MARK', 2013, 2, 'Majoituselinkeinon harjoittamiseen tarkoitetut loma-asunnot, jotka ovat rivi- tai ketjutaloja', 'Fritidshus avsedda för kommersiell logiverksamhet som är rad- eller kedjehus', false),
('LT', 2013, 3, 'Luhtitalot', 'Lofthus', false),
('MA', 2013, 3, 'Muut asuinkerrostalot', 'Övriga flervåningsbostadshus', false),
('T', 2013, 4, 'Toimistorakennukset', 'Kontorsbyggnader', false),
('TE', 2013, 4, 'Terveyskeskukset', 'Hälso(vårds)centraler', false),
('MT', 2013, 4, 'Muut terveydenhuoltorakennukset', 'Övriga hälsovårdsbyggnader', false),
('MH', 2013, 5, 'Myymälähallit', 'Butikshallar', false),
('LTK', 2013, 5, 'Liike- ja tavaratalot, kauppakeskukset', 'Affärs- och varuhus, handelscentra', false),
('MM', 2013, 5, 'Muut myymälärakennukset', 'Övriga butiksbyggnader', false),
('TOKK', 2013, 5, 'Teatterit, ooppera-, konsertti- ja kongressitalot', 'Teatrar, opera-, konsert- och kongresshus', false),
('E', 2013, 5, 'Elokuvateatterit', 'Biografer', false),
('KA', 2013, 5, 'Kirjastot ja arkistot', 'Bibliotek och arkiv', false),
('MUT', 2013, 5, 'Museot ja taidegalleriat', 'Museer och konstgallerier', false),
('N', 2013, 5, 'Näyttelyhallit', 'Utställningshallar', false),
('H', 2013, 6, 'Hotellit yms.', 'Hotell o. dyl.', false),
('A', 2013, 6, 'Asuntolat yms.', 'Kollektivbostadsbyggnader o. dyl.', false),
('V', 2013, 6, 'Vanhainkodit', 'Ålderdomshem', false),
('LK', 2013, 6, 'Lasten- ja koulukodit', 'Barnhem och skolhem', false),
('KH', 2013, 6, 'Kehitysvammaisten hoitolaitokset', 'Vårdanstalter för utvecklingsstörda', false),
('LP', 2013, 7, 'Lasten päiväkodit', 'Barndaghem', false),
('YOR', 2013, 7, 'Yleissivistävien oppilaitosten rakennukset', 'Byggnader för allmänbildande läroanstalter', false),
('AOR', 2013, 7, 'Ammatillisten oppilaitosten rakennukset', 'Byggnader för yrkesläroanstalter', false),
('K', 2013, 7, 'Korkeakoulurakennukset', 'Högskolebyggnader', false),
('TU', 2013, 7, 'Tutkimuslaitosrakennukset', 'Forskningsanstaltsbyggnader', false),
('TSSJ', 2013, 8, 'Tennis-, squash- ja sulkapallohallit', 'Tennis-, squash- och badmintonhallar', false),
('MMUJ', 2013, 8, 'Monitoimihallit ja muut urheiluhallit', 'Allaktivitetshallar och övriga idrottshallar', false),
('KE', 2013, 9, 'Keskussairaalat', 'Centralsjukhus', false),
('MS', 2013, 9, 'Muut sairaalat', 'Övriga sjukhus', false),
('MLR', 2013, 10, 'Liikenteen rakennukset', 'Trafikbyggnader', false),
('MUJH', 2013, 10, 'Uima- ja jäähallit', 'Simhallar, ishallar', false),
('MUMA', 2013, 11, 'Erilliset moottoriajoneuvosuojat', 'Fristående utrymmen för motorfordon', false),
('MRVR', 2013, 11, 'Varastorakennukset', 'Lagerbyggnader', false),
('TSS', 2013, 8, 'Tennis-, squash- ja sulkapallohallit (ennen 7/2016)', 'Tennis-, squash- och badmintonhallar (före 7/2016)', true),
('MMU', 2013, 8, 'Monitoimihallit ja muut urheiluhallit (ennen 7/2016)', 'Allaktivitetshallar och övriga idrottshallar (före 7/2016)', true),

('YAT', 2018, 1, 'Yhden asunnon talot', 'Hus med en bostad', false),
('KAT', 2018, 1, 'Kahden asunnon talot', 'Hus med två bostäder', false),
('KREP', 2018, 1, 'Ketjutalon osana olevat rakennukset ja muut erilliset pientalot', 'Byggnader som utgör en del av ett kedjehus och andra fristående småhus', false),
('RT', 2018, 1, 'Rivitalot', 'Radhus', false),
('AK2', 2018, 1, 'Asuinkerrostalot, joissa on asuinkerroksia enintään kahdessa kerroksessa', 'Flervåningsbostadshus med bostäder i högst två våningar', false),
('AK3', 2018, 2, 'Asuinkerrostalot, joissa on asuinkerroksia vähintään kolmessa kerroksessa', 'Flervåningsbostadshus med bostäder i minst tre våningar', false),
('T', 2018, 3, 'Toimistorakennukset', 'Kontorsbyggnader', false),
('TE', 2018, 3, 'Terveyskeskukset', 'Hälsocentraler', false),
('LR', 2018, 4, 'Liikerakennukset', 'Affärsbyggnader', false),
('TT', 2018, 4, 'Tavaratalot', 'Varuhus', false),
('KK', 2018, 4, 'Kauppakeskukset', 'Köpcentrum', false),
('MYR', 2018, 4, 'Myymälärakennukset (poislukien päivittäistavarakaupan alle 2000m2 yksiköt)', 'Butiksbyggnader (med undantag för livsmedelsaffärer på under 2000m2)', false),
('MH', 2018, 4, 'Myymälähallit', 'Butikshallar', false),
('TOKK', 2018, 4, 'Teatteri-, ooppera-, konsertti- ja kongressitalot', 'Teatrar, opera-, konsert- och kongresshus', false),
('E', 2018, 4, 'Elokuvateatterit', 'Biografer', false),
('KIR', 2018, 4, 'Kirjastot', 'Bibliotek', false),
('AR', 2018, 4, 'Arkistot', 'Arkiv', false),
('MU', 2018, 4, 'Museot', 'Museer', false),
('TG', 2018, 4, 'Taidegalleriat', 'Konstgallerier', false),
('N', 2018, 4, 'Näyttelyhallit', 'Utställningshallar', false),
('H', 2018, 5, 'Hotellit', 'Hotell', false),
('A', 2018, 5, 'Asuntolat', 'Internat', false),
('PT', 2018, 5, 'Palvelutalo', 'Servicehus', false),
('V', 2018, 5, 'Vanhainkodit', 'Ålderdomshem', false),
('HL', 2018, 5, 'Hoitolaitokset', 'Vårdinrättningar', false),
('OR', 2018, 6, 'Opetusrakennukset', 'Undervisningsbyggnader', false),
('PK', 2018, 6, 'Päiväkodit', 'Daghem', false),
('LH', 2018, 7, 'Liikuntahallit', 'Idrottshallar', false),
('S', 2018, 8, 'Sairaalat', 'Sjukhus', false),
('MRVR', 2018, 9, 'Varastorakennukset', 'Lagerbyggnader', false),
('MLR', 2018, 9, 'Liikenteen rakennukset', 'Trafikbyggnader', false),
('UH', 2018, 9, 'Uimahallit', 'Simhallar', false),
('JH', 2018, 9, 'Jäähallit', 'Ishallar', false),
('PTK', 2018, 9, 'Päivittäistavarakaupan alle 2000m2 yksiköt', 'Livsmedelsaffärer på under 2000m2', false),
('SR', 2018, 9, 'Siirtokelpoiset rakennukset', 'Flyttbara byggnader', false),
('MR', 2018, 9, 'Muut rakennukset', 'Övriga byggnader', false)
on conflict (id, versio) do update
  set label_fi = excluded.label_fi,
      label_sv = excluded.label_sv,
      deleted = excluded.deleted;