insert into karajaoikeus (id, ordinal, label_fi, label_sv)
values (0, 1, 'Ahvenanmaan karajaoikeus', 'Ålands tingsrätter'),
       (1, 2, 'Etelä-Karjalan karajaoikeus', 'Södrä Karelens tingsrätter'),
       (2, 3, 'Etelä-Pohjanmaan karajaoikeus', ' tingsrätter'),
       (3, 4, 'Etelä-Savon karajaoikeus', 'Södrä Savolax tingsrätter'),
       (4, 5, 'Helsingin karajaoikeus', 'Helsingfors tingsrätter'),
       (5, 6, 'Itä-Uudenmaan karajaoikeus', 'Östra Nylands tingsrätter'),
       (6, 7, 'Kainuun karajaoikeus', 'Kajanalands tingsrätter'),
       (7, 8, 'Kanta-Hämeen karajaoikeus', 'Egentliga Tavastlands tingsrätter'),
       (8, 9, 'Keski-Suomen karajaoikeus', 'Mellersta Finlands tingsrätter'),
       (9, 10, 'Kymenlaakson karajaoikeus', 'Kymmenedalens tingsrätter'),
       (10, 11, 'Lapin karajaoikeus', 'Lapplands tingsrätter'),
       (11, 12, 'Länsi-Uudenmaan karajaoikeus', 'Västrä Nylands tingsrätter'),
       (12, 13, 'Oulun karajaoikeus', 'Uleåborgs tingsrätter'),
       (13, 14, 'Pirkanmaan karajaoikeus', 'Birkalands tingsrätter'),
       (14, 15, 'Pohjanmaan karajaoikeus', 'Österbottens tingsrätter'),
       (15, 16, 'Pohjois-Karjalan karajaoikeus', 'Norra Karelens tingsrätter'),
       (16, 17, 'Pohjois-Savon karajaoikeus', 'Norra Savolax tingsrätter'),
       (17, 18, 'Päijät-Hameen karajaoikeus', 'Päijänne-Tavastlands tingsrätter'),
       (18, 19, 'Satakunnan karajaoikeus', 'Satakunta tingsrätter'),
       (19, 20, 'Varsinais-Suomen karajaoikeus', 'Egentliga Finlands tingsrätter')
on conflict (id) do update set label_fi = excluded.label_fi,
                               label_sv = excluded.label_sv,
                               ordinal  = excluded.ordinal;
